services:
  tor:
    image: leplusorg/tor:latest
    container_name: tor
    networks:
      - freenet
    environment:
      - SHELL_FORMAT_EXTRA=$${HS_DIR},$${HS_HOST},$${HS_PORT}
      - HS_DIR=/var/lib/tor/.tor/
      - HS_HOST=webserver
      - HS_PORT=80
    volumes:
      - ./torrc.template:/etc/tor/torrc.template
      - torkeys:/var/lib/tor/
      - ngxaccesslog:/var/log/tor/host.access.log
      # Uncomment the line below to add key files directory
      # - ./hiddenservices:/usr/tor/home/
    restart: always
  nginx:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./your-project/:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - freenet
    restart: always
volumes:
  torkeys:
  ngxaccesslog:
networks:
  freenet:
